/**
 * TypesWorkspaceView — catalogue view for `line_types` and
 * `transformer_types`.
 *
 * Two stacked sections per component type:
 *   1. **In this model** — read-only summary of rows the user has in the
 *      workbook, with usage counts and a jump-to-grid shortcut for editing.
 *   2. **PyPSA standard catalogue** — the 59 line types + 14 transformer
 *      types PyPSA ships out of the box (loaded from
 *      `src/config/pypsa_standard_types.json`, regenerated by
 *      `scripts/generate-pypsa-standard-types.mjs`). Each row has an
 *      "Add to model" button that appends it to the model sheet.
 */
import React, { useEffect, useMemo, useState } from 'react';
import { GridRow, WorkbookModel } from '../../shared/types';
import { stringValue } from '../../shared/utils/helpers';
import {
  PYPSA_STANDARD_LINE_TYPES,
  PYPSA_STANDARD_TRANSFORMER_TYPES,
  PYPSA_STANDARD_TYPES_SOURCE,
} from '../../constants/pypsa_standard_types';

const LINE_TYPE_COLS: Array<{ key: string; label: string; unit?: string }> = [
  { key: 'name', label: 'Name' },
  { key: 'f_nom', label: 'f_nom', unit: 'Hz' },
  { key: 'r_per_length', label: 'r/length', unit: 'Ω/km' },
  { key: 'x_per_length', label: 'x/length', unit: 'Ω/km' },
  { key: 'c_per_length', label: 'c/length', unit: 'nF/km' },
  { key: 'i_nom', label: 'i_nom', unit: 'kA' },
  { key: 'mounting', label: 'Mounting' },
  { key: 'cross_section', label: 'Cross section', unit: 'mm²' },
];

const TRANSFORMER_TYPE_COLS: Array<{ key: string; label: string; unit?: string }> = [
  { key: 'name', label: 'Name' },
  { key: 's_nom', label: 's_nom', unit: 'MVA' },
  { key: 'v_nom_0', label: 'v_nom_0', unit: 'kV' },
  { key: 'v_nom_1', label: 'v_nom_1', unit: 'kV' },
  { key: 'vsc', label: 'vsc', unit: '%' },
  { key: 'vscr', label: 'vscr', unit: '%' },
  { key: 'pfe', label: 'pfe', unit: 'kW' },
  { key: 'i0', label: 'i0', unit: '%' },
];

interface Props {
  model: WorkbookModel;
  onClose: () => void;
  onOpenTable: (sheet: 'line_types' | 'transformer_types') => void;
  onAddStandardType: (sheet: 'line_types' | 'transformer_types', row: GridRow) => void;
}

export function TypesWorkspaceView({ model, onClose, onOpenTable, onAddStandardType }: Props) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  const lineTypes = (model.line_types ?? []) as GridRow[];
  const transformerTypes = (model.transformer_types ?? []) as GridRow[];

  const lineUsage = countUsage(model, 'lines', lineTypes);
  const xfmrUsage = countUsage(model, 'transformers', transformerTypes);

  const modelLineNames = useMemo(() => new Set(lineTypes.map((r) => stringValue(r.name))), [lineTypes]);
  const modelXfmrNames = useMemo(() => new Set(transformerTypes.map((r) => stringValue(r.name))), [transformerTypes]);

  return (
    <div className="constraints-workspace">
      <div className="constraints-workspace-header">
        <div className="constraints-workspace-title">
          <h2>Component types</h2>
          <p>PyPSA-native <code>line_types</code> and <code>transformer_types</code> catalogues. Used by <code>lines.type</code> and <code>transformers.type</code> to pull in pre-set electrical parameters.</p>
        </div>
        <button className="tb-btn tb-btn--muted" onClick={onClose} title="Close (Esc)">Close</button>
      </div>

      <div className="constraints-workspace-body" style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        <CatalogueSection
          title="Line types in model"
          sheet="line_types"
          cols={LINE_TYPE_COLS}
          rows={lineTypes}
          usage={lineUsage}
          referencingSheet="lines"
          onOpenTable={onOpenTable}
        />
        <StandardCatalogueSection
          title="PyPSA standard line types"
          sheet="line_types"
          cols={LINE_TYPE_COLS}
          rows={PYPSA_STANDARD_LINE_TYPES}
          modelNames={modelLineNames}
          onAdd={(row) => onAddStandardType('line_types', row)}
        />
        <CatalogueSection
          title="Transformer types in model"
          sheet="transformer_types"
          cols={TRANSFORMER_TYPE_COLS}
          rows={transformerTypes}
          usage={xfmrUsage}
          referencingSheet="transformers"
          onOpenTable={onOpenTable}
        />
        <StandardCatalogueSection
          title="PyPSA standard transformer types"
          sheet="transformer_types"
          cols={TRANSFORMER_TYPE_COLS}
          rows={PYPSA_STANDARD_TRANSFORMER_TYPES}
          modelNames={modelXfmrNames}
          onAdd={(row) => onAddStandardType('transformer_types', row)}
        />
        <p className="types-catalogue-source">
          Standard catalogue from <code>{PYPSA_STANDARD_TYPES_SOURCE.repo}</code>
          {PYPSA_STANDARD_TYPES_SOURCE.commit ? ` @ ${PYPSA_STANDARD_TYPES_SOURCE.commit.slice(0, 7)}` : ''} ·
          regenerate with <code>node scripts/generate-pypsa-standard-types.mjs</code>.
        </p>
      </div>
    </div>
  );
}

function countUsage(model: WorkbookModel, sheet: 'lines' | 'transformers', types: GridRow[]): Record<string, number> {
  const counts: Record<string, number> = {};
  const known = new Set(types.map((row) => stringValue(row.name)));
  for (const row of (model[sheet] ?? []) as GridRow[]) {
    const t = stringValue(row.type);
    if (!t) continue;
    if (!known.has(t)) continue;
    counts[t] = (counts[t] ?? 0) + 1;
  }
  return counts;
}

function CatalogueSection({
  title,
  sheet,
  cols,
  rows,
  usage,
  referencingSheet,
  onOpenTable,
}: {
  title: string;
  sheet: 'line_types' | 'transformer_types';
  cols: Array<{ key: string; label: string; unit?: string }>;
  rows: GridRow[];
  usage: Record<string, number>;
  referencingSheet: string;
  onOpenTable: (sheet: 'line_types' | 'transformer_types') => void;
}) {
  return (
    <section className="constraints-workspace-section">
      <header className="constraints-workspace-section-header" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
        <div>
          <h3>{title} <span style={{ color: 'var(--muted)', fontWeight: 400 }}>· {rows.length} row{rows.length === 1 ? '' : 's'}</span></h3>
          <p>Referenced by <code>{referencingSheet}.type</code>. Edit in Model → Table → <code>{sheet}</code>.</p>
        </div>
        <button className="tb-btn" onClick={() => onOpenTable(sheet)}>Edit in table →</button>
      </header>
      {rows.length === 0 ? (
        <div className="constraints-empty">
          <p>No rows in <code>{sheet}</code>. Add from the PyPSA standard catalogue below, or in Model → Table.</p>
        </div>
      ) : (
        <div className="constraints-table-wrap">
          <table className="constraints-table">
            <thead>
              <tr>
                {cols.map((c) => (
                  <th key={c.key}>
                    {c.label}{c.unit ? <span style={{ color: 'var(--muted)', fontWeight: 400 }}> ({c.unit})</span> : null}
                  </th>
                ))}
                <th>Usage</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => {
                const name = stringValue(row.name);
                return (
                  <tr key={i}>
                    {cols.map((c) => (
                      <td key={c.key}>{stringValue(row[c.key]) || <span style={{ color: 'var(--muted)' }}>—</span>}</td>
                    ))}
                    <td>
                      {usage[name] ? (
                        <span style={{ color: 'var(--accent)' }}>{usage[name]} {referencingSheet}</span>
                      ) : (
                        <span style={{ color: 'var(--muted)' }}>unused</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

function StandardCatalogueSection({
  title,
  sheet,
  cols,
  rows,
  modelNames,
  onAdd,
}: {
  title: string;
  sheet: 'line_types' | 'transformer_types';
  cols: Array<{ key: string; label: string; unit?: string }>;
  rows: GridRow[];
  modelNames: Set<string>;
  onAdd: (row: GridRow) => void;
}) {
  const [filter, setFilter] = useState('');
  const filtered = useMemo(() => {
    if (!filter.trim()) return rows;
    const f = filter.toLowerCase();
    return rows.filter((row) => Object.values(row).some((v) => String(v ?? '').toLowerCase().includes(f)));
  }, [rows, filter]);

  return (
    <section className="constraints-workspace-section">
      <header className="constraints-workspace-section-header" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
        <div>
          <h3>{title} <span style={{ color: 'var(--muted)', fontWeight: 400 }}>· {rows.length} entries</span></h3>
          <p>Built-in PyPSA catalogue. Click <em>Add</em> to copy a row into <code>{sheet}</code>; duplicates are guarded.</p>
        </div>
        <input
          className="constraints-cell-input"
          style={{ maxWidth: 280 }}
          placeholder="Filter by name / mounting / voltage…"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
        />
      </header>
      <div className="constraints-table-wrap">
        <table className="constraints-table">
          <thead>
            <tr>
              {cols.map((c) => (
                <th key={c.key}>
                  {c.label}{c.unit ? <span style={{ color: 'var(--muted)', fontWeight: 400 }}> ({c.unit})</span> : null}
                </th>
              ))}
              <th aria-label="actions" />
            </tr>
          </thead>
          <tbody>
            {filtered.map((row, i) => {
              const name = stringValue(row.name);
              const alreadyInModel = modelNames.has(name);
              return (
                <tr key={i}>
                  {cols.map((c) => (
                    <td key={c.key}>{stringValue(row[c.key]) || <span style={{ color: 'var(--muted)' }}>—</span>}</td>
                  ))}
                  <td>
                    <button
                      className="tb-btn"
                      disabled={alreadyInModel}
                      title={alreadyInModel ? 'Already in model' : `Add ${name} to ${sheet}`}
                      onClick={() => onAdd(row)}
                    >
                      {alreadyInModel ? 'In model' : 'Add'}
                    </button>
                  </td>
                </tr>
              );
            })}
            {filtered.length === 0 && (
              <tr><td colSpan={cols.length + 1} style={{ color: 'var(--muted)', textAlign: 'center', padding: '12px 0' }}>No matches.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
