/** WRI GPPD importer metadata — same JSON the right-rail FilterPanel consumes. */
import type { DatabaseMeta } from 'lib/api/databases';

export const wriGppdMeta: DatabaseMeta = {
  id: 'wri_gppd',
  name: 'WRI Global Power Plant Database',
  category: 'generation',
  subcategory: 'Power plants (per-asset)',
  license: 'CC-BY 4.0',
  homepage: 'https://datasets.wri.org/dataset/globalpowerplantdatabase',
  version_hint: 'v1.3.0',
  description:
    '~35,000 power plants worldwide with name, capacity, fuel, lat/lon, owner, commissioning year. Single CSV, no auth.',
  targets: ['generators', 'buses', 'carriers'],
  available: true,
  country_coverage: 'global',
  filters: [
    {
      id: 'fuels',
      label: 'Fuels',
      kind: 'multiselect',
      default: [],
      options: [
        { value: 'Coal', label: 'Coal' },
        { value: 'Gas', label: 'Gas' },
        { value: 'Oil', label: 'Oil' },
        { value: 'Nuclear', label: 'Nuclear' },
        { value: 'Hydro', label: 'Hydro' },
        { value: 'Wind', label: 'Wind' },
        { value: 'Solar', label: 'Solar' },
        { value: 'Biomass', label: 'Biomass' },
        { value: 'Geothermal', label: 'Geothermal' },
        { value: 'Waste', label: 'Waste' },
        { value: 'Storage', label: 'Storage' },
        { value: 'Other', label: 'Other' },
      ],
      description: 'Leave empty to include every carrier.',
    },
    {
      id: 'min_capacity_mw',
      label: 'Min capacity',
      kind: 'number',
      default: 0,
      min: 0,
      step: 10,
      unit: 'MW',
    },
    {
      id: 'max_capacity_mw',
      label: 'Max capacity',
      kind: 'number',
      default: null,
      min: 0,
      step: 50,
      unit: 'MW',
      description: 'Leave empty for no upper bound.',
    },
    {
      id: 'commissioned_from',
      label: 'Commissioned from',
      kind: 'number',
      default: null,
      min: 1900,
      max: 2100,
      step: 1,
    },
    {
      id: 'commissioned_to',
      label: 'Commissioned to',
      kind: 'number',
      default: null,
      min: 1900,
      max: 2100,
      step: 1,
    },
    {
      id: 'owner_contains',
      label: 'Owner contains',
      kind: 'select',
      default: '',
      options: [],
      description: 'Substring filter on the owner column (case-insensitive).',
    },
  ],
};
