import { describe, it, expect } from '@jest/globals';
import * as fs from 'fs';
import * as path from 'path';
import { parseProjectWorkbook } from './workbook';

// Cross-language contract test: the BACKEND (backend/app/project_workbook.py)
// writes the project xlsx; the FRONTEND parser must read it losslessly. The
// fixture is generated by the backend writer (see the generator in that
// module's tests). If the two formats ever drift, this fails — which is the
// whole point: keep the Python writer and the TS parser in lock-step.
function fixtureBuffer(): ArrayBuffer {
  const file = path.join(__dirname, '__fixtures__', 'backend_project.xlsx');
  const buf = fs.readFileSync(file);
  // Copy into a fresh, exactly-sized ArrayBuffer — a Node Buffer is a view onto
  // a shared pool, so its raw `.buffer` carries unrelated bytes that confuse
  // SheetJS's format sniffing.
  const ab = new ArrayBuffer(buf.length);
  new Uint8Array(ab).set(buf);
  return ab;
}

describe('backend-built project workbook → frontend parser', () => {
  it('round-trips model inputs, solved outputs, and metadata', () => {
    const { model, outputs, metadata } = parseProjectWorkbook(fixtureBuffer());

    // Inputs — output-static columns split out, input columns kept.
    expect(model.generators.map((r) => r.name).sort()).toEqual(['gas', 'wind']);
    const wind = model.generators.find((r) => r.name === 'wind')!;
    expect(wind.p_nom).toBe(100);
    expect('p_nom_opt' in wind).toBe(false); // an output, not an input
    expect(model.buses.map((r) => r.name).sort()).toEqual(['n1', 'n2']);

    // Output static + series reconstructed.
    expect(outputs.static.generators.wind.p_nom_opt).toBe(120);
    expect(outputs.series['generators-p']).toHaveLength(2);
    expect(outputs.series['generators-p'][0].wind).toBe(80);
    expect(outputs.series['generators-p'][0].snapshot).toBe('2025-01-01T00:00:00');

    // Metadata.
    expect(metadata.runMeta).toEqual({ componentCounts: { generators: 2, buses: 2 } });
    expect(metadata.narrative).toEqual(['Solved in 2 snapshots.']);
    expect(metadata.constraints?.[0].metric).toBe('co2_cap');
  });
});
